### ISSUE TITLE
Some times the hover leaves a ghost

### ISSUE THREAD

**Issue by Jared-Sprague** [ScriptaGames/SquareOff#10]
clicking fast and moving fast at the same time leaves a ghost hover

**Comment by mwcz** [comment]
I worked on this for about an hour last night and couldn't get it working, but after I went to bed I thought of an idea that I think will work perfectly.  Instead using the button hover event to change a sprite sheet on the button, we can just make two sprites, one for each player, and move them around as needed.  That way they could never exist in two places at once!  I'll take a shot at implementing that today.

**Comment by Jared-Sprague** [comment]
@mwcz sounds great! this might be a good opportunity to clean up the hover sprite image too.  Since the current one is what I could do in about 2 minutes in gimp.

**Comment by mwcz** [comment]
But I like it!  It would be cool if it were animated but I wouldn't want to add that until after judging is complete.

**Comment by mwcz** [comment]
I fixed it!

**Comment by Jared-Sprague** [comment]
awesome!!
